version: 2


updates:
  # GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    target-branch: main

  # Python packages
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    target-branch: main
